### ISSUE TITLE
Path issue when creating new project on Windows

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind-vscode#43]
```
[DBUG: 14:01:29.526 UserProjectCreator.js:221]: Creation request
projectName:"gogo"
url:"https://github.com/microclimate-dev2ops/microclimateGoTemplate"
parentPath:"c:\codewind-workspace"
[ERRO: 14:01:29.566 CreateUserProjectCmd.js:75]: Error creating new project:  StatusCodeError: 400 - {"name":"ProjectInitializerError","code":"PATH_NOT_ABSOLUTE","message":"PATH_NOT_ABSOLUTE: Path to project must be an absolute path."}
	at new StatusCodeError (c:\Users\Administrator\Desktop\time\codewind-vscode\dev\node_modules\request-promise-core\lib\errors.js:32:15)
	at Request.module.exports.plumbing.callback (c:\Users\Administrator\Desktop\time\codewind-vscode\dev\node_modules\request-promise-core\lib\plumbing.js:104:33)
	at Request.RP$callback [as _callback] (c:\Users\Administrator\Desktop\time\codewind-vscode\dev\node_modules\request-promise-core\lib\plumbing.js:46:31)
	at Request.init.self.callback (c:\Users\Administrator\Desktop\time\codewind-vscode\dev\node_modules\request\request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.<anonymous> (c:\Users\Administrator\Desktop\time\codewind-vscode\dev\node_modules\request\request.js:1161:10)
	at Request.emit (events.js:182:13)
	at IncomingMessage.<anonymous> (c:\Users\Administrator\Desktop\time\codewind-vscode\dev\node_modules\request\request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1090:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by tetchel** [comment]
fixed #44
